#include "Nnue.h"

#include <cstring>
#include <fstream>
#include <iterator>
#include <vector>

// Generated by CMake from the default network file (empty if there is none).
extern const unsigned char kNagsEmbeddedNet[];
extern const unsigned long kNagsEmbeddedNetSize;

// The two hot kernels are also compiled for AVX2 and picked at run time
// where the toolchain supports it (GCC, x86-64 Linux); elsewhere the
// portable build is used.
#if defined(__GNUC__) && !defined(__clang__) && defined(__x86_64__) && defined(__linux__)
#define NAGS_NNUE_KERNEL __attribute__((target_clones("avx2", "default")))
#else
#define NAGS_NNUE_KERNEL
#endif

namespace nnue {

namespace {
Network fileNet, builtinNet;
bool fileLoaded = false, builtinLoaded = false, builtinTried = false, enabled = true;
std::string fileName;

template <class T>
T readLe(const unsigned char *p) {
    T v = 0;
    for (size_t i = 0; i < sizeof(T); ++i) v = static_cast<T>(v | (static_cast<T>(p[i]) << (8 * i)));
    return v;
}

bool parse(const unsigned char *data, size_t size, Network &net, std::string &error) {
    const size_t expected = 16 + 2 * (kFeatures * kHidden + kHidden + 2 * kHidden) + 4;
    if (size < 16 || std::memcmp(data, "NAGSNNUE", 8) != 0) {
        error = "not a NAGS NNUE file";
        return false;
    }
    if (readLe<uint32_t>(data + 8) != 1 || readLe<uint32_t>(data + 12) != kHidden) {
        error = "unsupported network version or size";
        return false;
    }
    if (size != expected) {
        error = "network file has the wrong size";
        return false;
    }
    const unsigned char *p = data + 16;
    for (int i = 0; i < kFeatures * kHidden; ++i, p += 2) net.ftWeights[i] = static_cast<int16_t>(readLe<uint16_t>(p));
    for (int i = 0; i < kHidden; ++i, p += 2) net.ftBias[i] = static_cast<int16_t>(readLe<uint16_t>(p));
    for (int i = 0; i < 2 * kHidden; ++i, p += 2) net.outWeights[i] = static_cast<int16_t>(readLe<uint16_t>(p));
    net.outBias = static_cast<int32_t>(readLe<uint32_t>(p));
    return true;
}

void select() {
    const Network *net = fileLoaded ? &fileNet : embedded();
    detail::active = enabled ? net : nullptr;
}
} // namespace

const Network *embedded() {
    if (!builtinTried) {
        builtinTried = true;
        std::string error;
        builtinLoaded = kNagsEmbeddedNetSize > 0 && parse(kNagsEmbeddedNet, kNagsEmbeddedNetSize, builtinNet, error);
    }
    return builtinLoaded ? &builtinNet : nullptr;
}

bool load(const std::string &path, std::string &error) {
    std::ifstream in(path, std::ios::binary);
    if (!in) {
        error = "cannot open '" + path + "'";
        return false;
    }
    std::vector<unsigned char> data((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
    if (!parse(data.data(), data.size(), fileNet, error)) return false;
    fileLoaded = true;
    fileName = path;
    select();
    return true;
}

void addFeature(Accumulator &acc, const Network &net, Piece p, int sq) {
    for (int persp = 0; persp < 2; ++persp) {
        const int16_t *w = net.ftWeights + featureIndex(persp, p, sq) * kHidden;
        int16_t *a = acc.v[persp];
        for (int i = 0; i < kHidden; ++i) a[i] = static_cast<int16_t>(a[i] + w[i]);
    }
}

NAGS_NNUE_KERNEL
int evaluate(const Accumulator &acc, Color stm) {
    const Network &net = *network();
    const int16_t *us = acc.v[colorIndex(stm)];
    const int16_t *them = acc.v[colorIndex(stm) ^ 1];
    int32_t sum = 0;
    for (int i = 0; i < kHidden; ++i) {
        int16_t a = us[i] < 0 ? 0 : us[i] > QA ? static_cast<int16_t>(QA) : us[i];
        int16_t b = them[i] < 0 ? 0 : them[i] > QA ? static_cast<int16_t>(QA) : them[i];
        sum += a * net.outWeights[i] + b * net.outWeights[kHidden + i];
    }
    return static_cast<int>((static_cast<int64_t>(sum) + net.outBias) * SCALE / (QA * QB));
}

NAGS_NNUE_KERNEL
void update(const Accumulator &prev, Accumulator &next, const Network &net, const DirtyPieces &d) {
    for (int persp = 0; persp < 2; ++persp) {
        const int16_t *in = prev.v[persp];
        int16_t *out = next.v[persp];
        const int16_t *a0 = net.ftWeights + featureIndex(persp, d.addPiece[0], d.addSquare[0]) * kHidden;
        const int16_t *r0 = net.ftWeights + featureIndex(persp, d.removePiece[0], d.removeSquare[0]) * kHidden;
        if (d.adds == 1 && d.removes == 1) { // quiet move
            for (int i = 0; i < kHidden; ++i) out[i] = static_cast<int16_t>(in[i] + a0[i] - r0[i]);
            continue;
        }
        const int16_t *r1 = net.ftWeights + featureIndex(persp, d.removePiece[1], d.removeSquare[1]) * kHidden;
        if (d.adds == 1) { // capture
            for (int i = 0; i < kHidden; ++i) out[i] = static_cast<int16_t>(in[i] + a0[i] - r0[i] - r1[i]);
            continue;
        }
        const int16_t *a1 = net.ftWeights + featureIndex(persp, d.addPiece[1], d.addSquare[1]) * kHidden;
        for (int i = 0; i < kHidden; ++i) // castling
            out[i] = static_cast<int16_t>(in[i] + a0[i] + a1[i] - r0[i] - r1[i]);
    }
}

void useEmbedded() {
    fileLoaded = false;
    fileName.clear();
    select();
}

std::string networkName() {
    if (fileLoaded) return fileName;
    return embedded() ? "embedded" : "";
}

bool setEnabled(bool on) {
    enabled = on;
    select();
    return network() != nullptr;
}

// Static initialisation: use the embedded network by default.
namespace {
const bool kInitialised = (select(), true);
}

} // namespace nnue
